### ISSUE TITLE
Remove at least one title

### ISSUE THREAD

**Issue by licaon-kter** [cloneconf/nedium#8]
eg: https://github.com/cloneconf/nedium/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/03.jpg

The title is shown 3 times in gradually bigger font, at least remove the middle one or the biggest one.

**Comment by cloneconf** [comment]
Well... I feel the bloat here...
Yes I am repeating the article name twice: first, second but not the third!
The third is **part** of the post itself.
However some check might solve it.

**Comment by cloneconf** [comment]
Hello @licaon-kter !

I did some changes and it seems better now ;)

![Screenshot_20220121_112027](https://user-images.githubusercontent.com/88058138/150510377-598b8864-02fc-4ab6-aadb-9e9204d9781f.jpg)
